import React, { Component } from 'react';
import PropTypes from 'prop-types';

import { API_TO_ICON_MAP } from './constants';
import './style.scss';


/**
* Icon generated by the Stories-API schema.
*/
export default class StoriesAPIIcon extends Component {
  static propTypes = {
    /** `StoriesAPI` data */
    data: PropTypes.object,
  };

  static defaultProps = {
    data: {source: 'fa', name: 'FaInfoCircle'},
  };

  render() {
    const { data } = this.props;
    
    const IconComponent = API_TO_ICON_MAP[data.source] || API_TO_ICON_MAP.fa;
    return  <IconComponent {...data} />;
  }
}
