import {
  arEG,
  enUS,
  esES,
  frFR,
} from '@mui/material/locale';

import type { LocalizationConfig } from '../types';

const localizationConfig: LocalizationConfig = {
  defaultLocale: 'en',
  localeSettings: {
    ar: {
      label: 'Arabic',
      muiThemeOptions: arEG,
      nativeLabel: 'العربية',
      rtl: true,
    },
    en: {
      label: 'English',
      muiThemeOptions: enUS,
      nativeLabel: 'English',
      rtl: false,
    },
    es: {
      label: 'Spanish',
      muiThemeOptions: esES,
      nativeLabel: 'Español',
      rtl: false,
    },
    fr: {
      label: 'French',
      muiThemeOptions: frFR,
      nativeLabel: 'Français',
      rtl: false,
    },
  },
  supportedLocales: ['en'],
  // Note: Convention is to use dot.notation for reference keys
  // and pascal_case for direct translations
  translations: {
    ar: {
      'collection.featuredStory.buttonLabel': 'عرض القصة المميزة',
      'collection.search.defaultPlaceholder': 'البحث في المجموعة...',
      'collection.storiesList.header': 'استكشف جمیع القصص من مجموعة {collection_name}',
      'search.defaultPlaceholder': 'بحث...',
      'search.suggestions.landingOverline': 'اقتراحات مختارة',
      'search.suggestions.landingTitle': 'استكشف من خلال عمليات البحث الشائعة',
      'story.collectionButtonLabel': 'استكشف المزيد من القصص',
      'storyId.actions.clipboard': 'نسخ المعرف إلى الحافظة',
      'storyId.actions.externalLink': 'الانتقال إلى الموقع الخارجي',
      'storyId.actions.story': 'الانتقال إلى القصة',
      collection: 'مجموعة',
      cancel: 'إلغاء',
      download: 'تنزيل',
      learn_more: 'اعرف المزيد',
      moment: 'لحظة',
      reset: 'إعادة تعيين',
      save: 'حفظ',
      save_failed: 'فشل الحفظ. يرجى إعادة التعيين أو المحاولة مرة أخرى.',
      save_success: 'تم الحفظ بنجاح!',
      see_more_options: 'عرض المزيد من الخيارات',
      select_language: 'اختر اللغة',
      story: 'قصة',
      view_collection: 'تصفح المجموعة',
      welcome: 'مرحبًا',
    },
    en: {
      'collection.featuredStory.buttonLabel': 'View Featured Story',
      'collection.search.defaultPlaceholder': 'Search collection...',
      'collection.storiesList.header': 'Explore All Stories from the {collection_name} Collection',
      'search.defaultPlaceholder': 'Search...',
      'search.suggestions.landingOverline': 'Curated suggestions',
      'search.suggestions.landingTitle': 'Explore with Popular Searches',
      'story.collectionButtonLabel': 'Explore More Stories',
      'storyId.actions.clipboard': 'Copy to Clipboard',
      'storyId.actions.externalLink': 'Go to External Site',
      'storyId.actions.story': 'Go to Story',
      collection: 'collection',
      cancel: 'Cancel',
      download: 'Download',
      learn_more: 'Learn More',
      moment: 'moment',
      reset: 'Reset',
      save: 'Save',
      save_failed: 'Failed to save. Please reset or try again',
      save_success: 'Saved Successfully!',
      see_more_options: 'See more options',
      select_language: 'Select Language',
      story: 'story',
      view_collection: 'View Collection',
      welcome: 'Welcome',
    },
    es: {
      'collection.featuredStory.buttonLabel': 'Ver historia destacada',
      'collection.search.defaultPlaceholder': 'Buscar en la colección...',
      'collection.storiesList.header': 'Explorar todas las historias de la colección {collection_name}',
      'search.defaultPlaceholder': 'Buscar...',
      'search.suggestions.landingOverline': 'Sugerencias seleccionadas',
      'search.suggestions.landingTitle': 'Explora con búsquedas populares',
      'story.collectionButtonLabel': 'Explorar más historias',
      'storyId.actions.clipboard': 'Copiar ID al portapapeles',
      'storyId.actions.externalLink': 'Ir al sitio externo',
      'storyId.actions.story': 'Ir a la historia',
      collection: 'colección',
      cancel: 'Cancelar',
      moment: 'momento',
      save: 'Guardar',
      select_language: 'Seleccionar idioma',
      story: 'historia',
      welcome: 'Bienvenido',
    },
    fr: {
      'collection.search.defaultPlaceholder': 'Rechercher dans la collection...',
      'collection.storiesList.header': 'Explorer toutes les histoires de la collection {collection_name}',
      'search.defaultPlaceholder': 'Rechercher...',
      'search.suggestions.landingOverline': 'Suggestions sélectionnées',
      'search.suggestions.landingTitle': 'Explorez les recherches populaires',
      'story.collectionButtonLabel': 'Explorer plus d\'histoires',
      'storyId.actions.clipboard': 'Copier l\'ID dans le presse-papiers',
      'storyId.actions.externalLink': 'Aller vers le site externe',
      'storyId.actions.story': 'Aller à l\'histoire',
      cancel: 'Annuler',
      collection: 'collection',
      download: 'Télécharger',
      learn_more: 'En savoir plus',
      moment: 'moment',
      reset: 'Réinitialiser',
      save: 'Enregistrer',
      save_failed: "Échec de l'enregistrement. Veuillez réinitialiser ou réessayer.",
      save_success: 'Enregistré avec succès !',
      see_more_options: 'Voir plus d’options',
      select_language: 'Choisir la langue',
      story: 'histoire',
      view_collection: 'Voir la collection',
      welcome: 'Bienvenue',
    },

  },
};

export default localizationConfig;
