const API_TO_MOMENT_MAP = Object.freeze({
  award: 'AwardMoment',
  audio: 'AudioMoment',
  education: 'EducationMoment',
  employer: 'EmployerMoment',
  iframe: 'IFrameMoment',
  image: 'ImageMoment',
  library: 'LibraryMoment',
  map: 'MapMoment',
  membership: 'MembershipMoment',
  mirador: 'MiradorMoment',
  named_after: 'NamedAfterMoment',
  pdf: 'PDFMoment',
  people: 'PeopleMoment',
  reference: 'ReferenceMoment',
  software_heritage: 'SoftwareHeritageMoment',
  stat: 'StatMoment',
  timeline: 'TimelineMoment',
  video: 'VideoMoment',
  wikidata: 'WikidataMoment',
  wikipedia: 'WikipediaMoment',
  youtube: 'YouTubeMoment',
});
export default API_TO_MOMENT_MAP;
